# Generated by Django 4.0.1 on 2022-02-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='0fd7d1', max_length=50),
        ),
    ]
